# Dynamic Mode Detection Pattern
# Real-time mode activation based on context analysis

mode_detection:
  brainstorming:
    triggers:
      - "vague project requests"
      - "exploration keywords"
      - "uncertainty indicators"
      - "new project discussions"
    patterns:
      - "I want to build"
      - "thinking about"
      - "not sure"
      - "explore"
      - "brainstorm"
      - "figure out"
    confidence_threshold: 0.7
    activation_hooks: ["session_start", "pre_tool_use"]
    coordination:
      command: "/sc:brainstorm"
      mcp_servers: ["sequential", "context7"]
      
  task_management:
    triggers:
      - "multi-step operations"
      - "build/implement keywords"
      - "system-wide scope"
      - "delegation indicators"
    patterns:
      - "build"
      - "implement"
      - "create"
      - "system"
      - "comprehensive"
      - "multiple files"
    confidence_threshold: 0.8
    activation_hooks: ["pre_tool_use", "subagent_stop"]
    coordination:
      wave_orchestration: true
      delegation_patterns: true
      
  token_efficiency:
    triggers:
      - "context usage >75%"
      - "large-scale operations"
      - "resource constraints"
      - "brevity requests"
    patterns:
      - "compressed"
      - "brief"
      - "optimize"
      - "efficient"
      - "reduce"
    confidence_threshold: 0.75
    activation_hooks: ["pre_compact", "session_start"]
    coordination:
      compression_algorithms: true
      selective_preservation: true
      
  introspection:
    triggers:
      - "self-analysis requests"
      - "framework discussions"
      - "meta-cognitive needs"
      - "error analysis"
    patterns:
      - "analyze reasoning"
      - "framework"
      - "meta"
      - "introspect"
      - "self-analysis"
    confidence_threshold: 0.6
    activation_hooks: ["post_tool_use"]
    coordination:
      meta_cognitive_analysis: true
      reasoning_validation: true

adaptive_learning:
  pattern_refinement:
    enabled: true
    learning_rate: 0.1
    feedback_integration: true
    
  user_adaptation:
    track_preferences: true
    adapt_thresholds: true
    personalization: true
    
  effectiveness_tracking:
    mode_success_rate: true
    user_satisfaction: true
    performance_impact: true

cross_mode_coordination:
  simultaneous_modes:
    - ["task_management", "token_efficiency"]
    - ["brainstorming", "introspection"]
    
  mode_transitions:
    brainstorming_to_task_management:
      trigger: "requirements clarified"
      confidence: 0.8
      
    task_management_to_introspection:
      trigger: "complex issues encountered"
      confidence: 0.7