# Mode detection patterns for SuperClaude-Lite
mode_detection:
  brainstorming:
    enabled: true
    trigger_patterns:
      - "I want to build"
      - "thinking about"
      - "not sure"
      - "maybe.*could"
      - "brainstorm"
      - "explore"
      - "figure out"
      - "unclear.*requirements"
      - "ambiguous.*needs"
    confidence_threshold: 0.7
    auto_activate: true
  
  task_management:
    enabled: true  
    trigger_patterns:
      - "multiple.*tasks"
      - "complex.*system"
      - "build.*comprehensive"
      - "coordinate.*work"
      - "large-scale.*operation"
      - "manage.*operations"
      - "comprehensive.*refactoring"
      - "authentication.*system"
    confidence_threshold: 0.7
    auto_activate: true
    auto_activation_thresholds:
      file_count: 3
      complexity_score: 0.4
  
  token_efficiency:
    enabled: true
    trigger_patterns:
      - "brief"
      - "concise"
      - "compressed"
      - "efficient.*output"
      - "token.*optimization"
      - "short.*response"
      - "running.*low.*context"
    confidence_threshold: 0.75
    auto_activate: true
  
  introspection:
    enabled: true
    trigger_patterns:
      - "analyze.*reasoning"
      - "examine.*decision"
      - "reflect.*on"
      - "meta.*cognitive"
      - "thinking.*process"
      - "reasoning.*process"
      - "decision.*made"
    confidence_threshold: 0.6
    auto_activate: true