# Orchestrator routing patterns
routing_patterns:
  context7:
    triggers:
      - "library.*documentation"
      - "framework.*patterns"
      - "react|vue|angular"
      - "official.*way"
      - "React Query"
      - "integrate.*library"
    capabilities: ["documentation", "patterns", "integration"]
    priority: "medium"
    
  sequential:
    triggers:
      - "analyze.*complex"
      - "debug.*systematic"
      - "troubleshoot.*bottleneck"
      - "investigate.*root"
      - "debug.*why"
      - "detailed.*analysis"
      - "running.*slowly"
      - "performance.*bottleneck"
      - "bundle.*size"
    capabilities: ["analysis", "debugging", "systematic"]
    priority: "high"
    
  magic:
    triggers:
      - "component.*ui"
      - "responsive.*modal"
      - "navigation.*component"
      - "mobile.*friendly"
      - "responsive.*dashboard"
      - "charts.*real-time"
      - "build.*dashboard"
    capabilities: ["ui", "components", "responsive"]
    priority: "medium"
    
  playwright:
    triggers:
      - "test.*workflow"
      - "browser.*automation"
      - "cross-browser.*testing"
      - "performance.*testing"
      - "end-to-end.*tests"
      - "checkout.*flow"
      - "e2e.*tests"
    capabilities: ["testing", "automation", "e2e"]
    priority: "medium"
    
  morphllm:
    triggers:
      - "edit.*file"
      - "simple.*modification"
      - "quick.*change"
    capabilities: ["editing", "modification"]
    priority: "low"
    
  serena:
    triggers:
      - "refactor.*codebase"
      - "complex.*analysis"
      - "multi.*file"
      - "refactor.*entire"
      - "new.*API.*patterns"
    capabilities: ["refactoring", "semantic", "large-scale"]
    priority: "high"

# Auto-activation thresholds
auto_activation:
  complexity_thresholds:
    enable_delegation:
      file_count: 3
      directory_count: 2
      complexity_score: 0.4
    enable_sequential:
      complexity_score: 0.6
    enable_validation:
      risk_level: ["high", "critical"]

# Hybrid intelligence selection
hybrid_intelligence:
  morphllm_vs_serena:
    morphllm_criteria:
      file_count_max: 10
      complexity_max: 0.6
      preferred_operations: ["edit", "modify", "simple_refactor"]
    serena_criteria:
      file_count_min: 5
      complexity_min: 0.4
      preferred_operations: ["refactor", "analyze", "extract", "move"]

# Performance optimization
performance_optimization:
  resource_management:
    token_threshold_percent: 75