# SuperClaude-Lite Performance Configuration
# Performance targets, thresholds, and optimization strategies

# Hook Performance Targets
hook_targets:
  session_start:
    target_ms: 50
    warning_threshold_ms: 75
    critical_threshold_ms: 100
    optimization_priority: "critical"
    
  pre_tool_use:
    target_ms: 200
    warning_threshold_ms: 300
    critical_threshold_ms: 500
    optimization_priority: "high"
    
  post_tool_use:
    target_ms: 100
    warning_threshold_ms: 150
    critical_threshold_ms: 250
    optimization_priority: "medium"
    
  pre_compact:
    target_ms: 150
    warning_threshold_ms: 200
    critical_threshold_ms: 300
    optimization_priority: "high"
    
  notification:
    target_ms: 100
    warning_threshold_ms: 150
    critical_threshold_ms: 200
    optimization_priority: "medium"
    
  stop:
    target_ms: 200
    warning_threshold_ms: 300
    critical_threshold_ms: 500
    optimization_priority: "low"
    
  subagent_stop:
    target_ms: 150
    warning_threshold_ms: 200
    critical_threshold_ms: 300
    optimization_priority: "medium"

# System Performance Targets
system_targets:
  overall_session_efficiency: 0.75
  mcp_coordination_efficiency: 0.70
  compression_effectiveness: 0.50
  learning_adaptation_rate: 0.80
  user_satisfaction_target: 0.75
  
  resource_utilization:
    memory_target_mb: 100
    memory_warning_mb: 150
    memory_critical_mb: 200
    
    cpu_target_percent: 40
    cpu_warning_percent: 60
    cpu_critical_percent: 80
    
    token_efficiency_target: 0.40
    token_warning_threshold: 0.20
    token_critical_threshold: 0.10

# MCP Server Performance
mcp_server_performance:
  context7:
    activation_target_ms: 150
    response_target_ms: 500
    cache_hit_ratio_target: 0.70
    quality_score_target: 0.90
    
  sequential:
    activation_target_ms: 200
    response_target_ms: 1000
    analysis_depth_target: 0.80
    reasoning_quality_target: 0.85
    
  magic:
    activation_target_ms: 120
    response_target_ms: 800
    component_quality_target: 0.85
    generation_speed_target: 0.75
    
  playwright:
    activation_target_ms: 300
    response_target_ms: 2000
    test_reliability_target: 0.90
    automation_efficiency_target: 0.80
    
  morphllm:
    activation_target_ms: 80
    response_target_ms: 400
    edit_accuracy_target: 0.95
    processing_efficiency_target: 0.85
    
  serena:
    activation_target_ms: 100
    response_target_ms: 600
    semantic_accuracy_target: 0.90
    memory_efficiency_target: 0.80

# Compression Performance
compression_performance:
  target_compression_ratio: 0.50
  quality_preservation_minimum: 0.95
  processing_speed_target_chars_per_ms: 100
  
  level_targets:
    minimal:
      compression_ratio: 0.15
      quality_preservation: 0.98
      processing_time_factor: 1.0
      
    efficient:
      compression_ratio: 0.40
      quality_preservation: 0.95
      processing_time_factor: 1.2
      
    compressed:
      compression_ratio: 0.60
      quality_preservation: 0.90
      processing_time_factor: 1.5
      
    critical:
      compression_ratio: 0.75
      quality_preservation: 0.85
      processing_time_factor: 1.8
      
    emergency:
      compression_ratio: 0.85
      quality_preservation: 0.80
      processing_time_factor: 2.0

# Learning Engine Performance
learning_performance:
  adaptation_response_time_ms: 200
  pattern_detection_accuracy: 0.80
  effectiveness_prediction_accuracy: 0.75
  
  learning_rates:
    user_preference_learning: 0.85
    operation_pattern_learning: 0.80
    performance_optimization_learning: 0.75
    error_recovery_learning: 0.90
    
  memory_efficiency:
    learning_data_compression_ratio: 0.30
    memory_cleanup_efficiency: 0.90
    cache_hit_ratio: 0.70

# Quality Gate Performance
quality_gate_performance:
  validation_speed_targets:
    syntax_validation_ms: 50
    type_analysis_ms: 100
    code_quality_ms: 150
    security_assessment_ms: 200
    performance_analysis_ms: 250
    
  accuracy_targets:
    rule_compliance_detection: 0.95
    principle_alignment_assessment: 0.90
    quality_scoring_accuracy: 0.85
    security_vulnerability_detection: 0.98
    
  comprehensive_validation_target_ms: 500

# Task Management Performance
task_management_performance:
  delegation_efficiency_targets:
    file_based_delegation: 0.65
    folder_based_delegation: 0.70
    auto_delegation: 0.75
    
  wave_orchestration_targets:
    coordination_overhead_max: 0.20
    wave_synchronization_efficiency: 0.85
    parallel_execution_speedup: 1.50
    
  task_completion_targets:
    success_rate: 0.90
    quality_score: 0.80
    time_efficiency: 0.75

# Mode-Specific Performance
mode_performance:
  brainstorming:
    dialogue_response_time_ms: 300
    convergence_efficiency: 0.80
    brief_generation_quality: 0.85
    user_satisfaction_target: 0.85
    
  task_management:
    coordination_overhead_max: 0.15
    delegation_efficiency: 0.70
    parallel_execution_benefit: 1.40
    analytics_generation_time_ms: 500
    
  token_efficiency:
    compression_processing_time_ms: 150
    efficiency_gain_target: 0.40
    quality_preservation_target: 0.95
    user_acceptance_rate: 0.80
    
  introspection:
    analysis_depth_target: 0.80
    insight_quality_target: 0.75
    transparency_effectiveness: 0.85
    learning_value_target: 0.70

# Performance Monitoring
performance_monitoring:
  real_time_tracking:
    enabled: true
    sampling_interval_ms: 100
    metric_aggregation_window_s: 60
    alert_threshold_breaches: 3
    
  metrics_collection:
    execution_times: true
    resource_utilization: true
    quality_scores: true
    user_satisfaction: true
    error_rates: true
    
  alerting:
    performance_degradation: true
    resource_exhaustion: true
    quality_threshold_breach: true
    user_satisfaction_drop: true
    
  reporting:
    hourly_summaries: true
    daily_analytics: true
    weekly_trends: true
    monthly_optimization_reports: true

# Optimization Strategies
optimization_strategies:
  caching:
    intelligent_caching: true
    cache_warming: true
    predictive_loading: true
    cache_invalidation: "smart"
    
  parallel_processing:
    auto_detection: true
    optimal_concurrency: "dynamic"
    load_balancing: "intelligent"
    resource_coordination: "adaptive"
    
  resource_management:
    memory_optimization: true
    cpu_optimization: true
    token_optimization: true
    storage_optimization: true
    
  adaptive_performance:
    dynamic_target_adjustment: true
    context_aware_optimization: true
    learning_based_improvement: true
    user_preference_integration: true

# Performance Thresholds
performance_thresholds:
  green_zone: # 0-70% resource usage
    all_optimizations_available: true
    proactive_caching: true
    full_feature_set: true
    normal_verbosity: true
    
  yellow_zone: # 70-85% resource usage
    efficiency_mode_activation: true
    cache_optimization: true
    reduced_verbosity: true
    non_critical_feature_deferral: true
    
  orange_zone: # 85-95% resource usage
    aggressive_optimization: true
    compression_activation: true
    feature_reduction: true
    essential_operations_only: true
    
  red_zone: # 95%+ resource usage
    emergency_mode: true
    maximum_compression: true
    minimal_features: true
    critical_operations_only: true

# Fallback Performance
fallback_performance:
  graceful_degradation:
    feature_prioritization: true
    quality_vs_speed_tradeoffs: "intelligent"
    user_notification: true
    automatic_recovery: true
    
  emergency_protocols:
    resource_exhaustion: "immediate_compression"
    timeout_protection: "operation_cancellation"
    error_cascade_prevention: "circuit_breaker"
    
  recovery_strategies:
    performance_restoration: "gradual"
    feature_reactivation: "conditional"
    quality_normalization: "monitored"

# Benchmarking and Testing
benchmarking:
  performance_baselines:
    establish_on_startup: true
    regular_recalibration: true
    environment_specific: true
    
  load_testing:
    synthetic_workloads: true
    stress_testing: true
    endurance_testing: true
    
  regression_testing:
    performance_regression_detection: true
    quality_regression_detection: true
    feature_regression_detection: true
    
# Integration Performance
integration_performance:
  cross_hook_coordination: 0.90
  mcp_server_orchestration: 0.85
  mode_switching_efficiency: 0.80
  learning_engine_responsiveness: 0.85
  
  end_to_end_targets:
    session_initialization: 500 # ms
    complex_operation_completion: 5000 # ms
    session_termination: 1000 # ms
    
  system_health_indicators:
    overall_efficiency: 0.75
    user_experience_quality: 0.80
    system_reliability: 0.95
    adaptation_effectiveness: 0.70